# Frontend Dockerfile
FROM python:3.9-alpine

WORKDIR /app

# Copy frontend files
COPY index.html .
COPY main.js .
COPY style.css .
COPY images/ ./images/

# Copy server launcher
COPY serve.py .

# Expose frontend port
EXPOSE 5500

# Start server
CMD ["python3", "serve.py"]
